### ISSUE TITLE
Examples don't work.

### ISSUE THREAD

**Issue by matiit** [joseluisq/gimage#15]
- Ellipse example - generates empty, transparent png file.
 - Rectangle example - generates empty, transparent png file.
 - Card example, text is missing on the image:
![image](https://cloud.githubusercontent.com/assets/138194/25559753/f7060054-2d38-11e7-80c7-8af27cb9cd12.png)

My setup:
PHP 7.0.15, Linux.

**Comment by joseluisq** [comment]
Now, it's solved in [v3.0.2](https://github.com/joseluisq/gimage/blob/master/CHANGELOG.md). Thanks for your feedback!

**Comment by matiit** [comment]
I can confirm it's fixed. 

Great!

**Comment by joseluisq** [comment]
Hey @matiit I was wondering if you're interested in become a maintainer of this library?
Please confirm if you are interested in.

**Comment by matiit** [comment]
Hey, @joseluisq 
sorry for late reply, I do not have a time for it, sorry

**Comment by joseluisq** [comment]
No problem, if you have time in the future feel free to contribute. 👍

**Comment by matiit** [comment]
Definitely :+1:
