### ISSUE TITLE
How I can remove the spacing in the text by using my font?

### ISSUE THREAD

**Issue by YeltsinReyes** [joseluisq/gimage#2]
Do I have a very large space when I put a very long with my fon text, as I remove this ??

Example:
![screenshot](https://cloud.githubusercontent.com/assets/13794459/12250766/f36d16da-b89f-11e5-8fc8-a78490717325.png)

**Comment by joseluisq** [comment]
I can't to see the problem in your image. Can you be more specific?

**Comment by YeltsinReyes** [comment]
the text is quite separate, as I hit it more?

**Comment by joseluisq** [comment]
You can separate your text in several instances of `GText('Text1')`, etc

**Comment by YeltsinReyes** [comment]
There is no option to remove the space?

**Comment by joseluisq** [comment]
Do you have the code of your example?

**Comment by YeltsinReyes** [comment]
It is this, eh just by changing the font

https://github.com/quintana-dev/gimage/blob/master/examples/card.php

**Comment by joseluisq** [comment]
Pienso mejor escribir en español porque no logro entender tu problema :smile: 
Lo que he podido leer es que tienes algún espacio en el texto y quieres quitarlo.
Te decía si puedes ser **más especifico** al explicar tu problema con el ejemplo de la tarjeta.

**Comment by YeltsinReyes** [comment]
Oh se me olvido que hablas español. :)
Yo eh usando el ejemplo de card.php y solo le eh cambiando el tipo de fuente, entonce al ser el texto
muy largo hace un párrafo pero queda un espacio muy grande entre las letras, quería saber
si se puede eliminar ese espacio?

**Comment by joseluisq** [comment]
¿Te refieres a espacio entre cada letra o espacio entre lineas (espaciado vertical entre lineas)?

**Comment by joseluisq** [comment]
¿Puedes compartir una captura de tu imagen generada con esa fuente? Quizá es problema de tu fuente

**Comment by YeltsinReyes** [comment]
Si perdón, el espacio entre lineas hay una opción para reducirlas estas lineas?

**Comment by joseluisq** [comment]
Entiendo. Obvia la captura.

**Comment by YeltsinReyes** [comment]
No se puede hacer nada para solucionarlo.?

**Comment by joseluisq** [comment]
Por ahora el `GImage` no soporta dicha opción, pero es posible reducir manualmente el interlineado  (line-height) del texto directamente modificando la función [getWrappedText()](https://github.com/quintana-dev/gimage/blob/master/src/gimage/gtext.php#L190-L206) en la clase `GText` 

Podrías revisar este enlace http://stackoverflow.com/questions/6926613/php-imagettftext-letter-spacing e implementarlo tu mismo.
También puedes agregar un nuevo Issue aquí para implementarlo luego o si deseas eres libre de hacer un Pull Request al repositorio de `GImage`.

Saludos

**Comment by YeltsinReyes** [comment]
Ok man muchas gracias, veré si puedo solucionarlo con es función.

Saludos!

**Comment by joseluisq** [comment]
He agregado soporte para line-height.
Puedes revisar el issue https://github.com/quintana-dev/gimage/issues/3.
