### ISSUE TITLE
Line-height support for GText

### ISSUE THREAD

**Issue by joseluisq** [joseluisq/gimage#3]
Add support for _line-height_ in GText class.

**Comment by joseluisq** [comment]
Covered at [v1.5.1](https://github.com/quintana-dev/gimage/releases/tag/1.5.1) release.
Example:

``` php
<?php
$text = new GText('Lorem ipsum dolor sit amet, consectetur adipiscing elit.');
$text->setWidth(400);
$text->setHeight(250);

// Set line-height
$text->setLineHeight(1.2);

```

**Comment by YeltsinReyes** [comment]
Muchísimas gracias man, yo soy novato en programación por eso no puedo hacer muchas cosas!!

Saludos! (y)

**Comment by joseluisq** [comment]
:+1:
