### ISSUE TITLE
Project opens for new maintainers

### ISSUE THREAD

**Issue by joseluisq** [joseluisq/gimage#34]
Due I don't have time to maintain this project. I'm opening this issue for people interested on it as maintainer.
If you would like to collaborate with this project, please let me to know here.

**Comment by ssheduardo** [comment]
Qué cambios se tendría que hacer para PHP8??

**Comment by joseluisq** [comment]
No he probado la librería durante bastante tiempo, pero imagino no muchos cambios significativos (quizá algo de updates en alguna API, tests, ajustes en CI?
Puedes hacer un fork y ver que tal te va. O si estas interesado en mantener el proyecto, solo avísame.
Por el momento, yo sólo podría ayudar con reviews.

**Comment by ssheduardo** [comment]
Lo estoy usando con Laravel la verdad que bien aunque ahora estoy actualizando la versión de Laravel a 8.0, ya veo que no hay soporte para PHP8 y cuando intente pasar a dicha versión no sera compatible,
Dime más o menos que hacer para cuando tenga tiempo ir haciendo pruebas, si me guías en algo genial para ayudar en lo que se pueda.

**Comment by joseluisq** [comment]
> Lo estoy usando con Laravel la verdad que bien aunque ahora estoy actualizando la versión de Laravel a 8.0, ya veo que no hay soporte para PHP8 y cuando intente pasar a dicha versión no sera compatible, Dime más o menos que hacer para cuando tenga tiempo ir haciendo pruebas, si me guías en algo genial para ayudar en lo que se pueda.

Seguro, aquí algunos pasos:

- Fork al repo y ejecuta las pruebas con PHP 8.0 y 8.1 (PHPUnit) ejecutando `composer install && vendor/bin/phpunit`
- Si usas Docker seria mucho mas sencillo, yo mantengo esta imagen que te puede servir https://github.com/joseluisq/alpine-php-fpm / o usa el método que mejor te parezca.
- Si aparecen errores durante las pruebas, trata de corregirlas y luego agrégalas a un branch `php8-support`
- Finalmente, crea un Pull Request (como Draft) aquí en Github, asi luego puedo revisarlo y te asistiré si es necesario.

**Comment by ssheduardo** [comment]
> > Lo estoy usando con Laravel la verdad que bien aunque ahora estoy actualizando la versión de Laravel a 8.0, ya veo que no hay soporte para PHP8 y cuando intente pasar a dicha versión no sera compatible, Dime más o menos que hacer para cuando tenga tiempo ir haciendo pruebas, si me guías en algo genial para ayudar en lo que se pueda.
> 
> Seguro, aquí algunos pasos:
> 
> * Fork al repo y ejecuta las pruebas con PHP 8.0 y 8.1 (PHPUnit) ejecutando `composer install && vendor/bin/phpunit`
> * Si usas Docker seria mucho mas sencillo, yo mantengo esta imagen que te puede servir https://github.com/joseluisq/alpine-php-fpm / o usa el método que mejor te parezca.
> * Si aparecen errores durante las pruebas, trata de corregirlas y luego agrégalas a un branch `php8-support`
> * Finalmente, crea un Pull Request (como Draft) aquí en Github, asi luego puedo revisarlo y te asistiré si es necesario.

Genial, estaba revisando tus imágenes, yo también tengo esas versiones en mi proyecto pero voy a probar las tuyas que me gusta estar tocando.
Chevere entonces en ese caso, ahora la duda que aplico es al usar la imagen docker luego con un composer require me llamo el paquete y ahí realizo las pruebas o como me recomiendas, como partiré del fork.
En resumen para haría para hacer las pruebas docker y a la vez un pull request del paquete.
No se si me explique bien.

Te debo un ceviche si sale bien todo.

**Comment by joseluisq** [comment]
> Chevere entonces en ese caso, ahora la duda que aplico es al usar la imagen docker luego con un composer require me llamo el paquete y ahí realizo las pruebas o como me recomiendas, como partiré del fork.

Las pruebas las puedes hacer directamente en tu maquina local primero asi como si necesitas usar Docker u otra herramienta.

Lo que enviarías al PR serian sólo las correcciones al código fuente si son necesarias como resultado de unit tests fallidos (necesitas confirmar eso).

No es necesario enviar tu setup Docker u otros archivos al PR, eso será útil para tus pruebas locales.
Yo te asistiría con la configuración del CI aquí en el repo para ejecutar los tests unitarios con PHP 8.0 y 8.1 automáticamente.

**Comment by joseluisq** [comment]
I have decided that I will resume maintenance for the library. That means some improvements to the code base as well as support for the newest PHP "7.4", 8.0 and 8.1.

**Comment by joseluisq** [comment]
Release [v4.0.0](https://github.com/joseluisq/gimage/releases/tag/v4.0.0)
