### ISSUE TITLE
How can I use this library in Codeigniter?

### ISSUE THREAD

**Issue by YeltsinReyes** [joseluisq/gimage#8]
Hello, not I am very good in programming or in codeigniter but I would like to know as I can use this liberia in codeigniter?

**Comment by joseluisq** [comment]
I recommend that you load the library via [composer](https://getcomposer.org/) `autoload`. 
Check out this tutorial: https://github.com/joseluisq/codeigniter-composer-boilerplate.

**Comment by YeltsinReyes** [comment]
@joseluisq your example only shows me this: [image](http://image.prntscr.com/image/4f819726772c4b9fa88755261d923c3d.png)

**Comment by joseluisq** [comment]
Can you show your code?
